---
engines:
  brakeman:
    enabled: true
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  eslint:
    enabled: false
  fixme:
    enabled: false
  rubocop:
    enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
exclude_paths:
- "config/"
- "db/"
- "spec/"
- "lib/alchemy/upgrader/"
- "lib/rails/"
